apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
    replicas: 1
    selector:
      matchLabels:
        app: minio
    template:
      metadata:
        labels:
          app: minio
      spec:
        containers:
          - name: minio
            image: minio/minio
            args: ["server", "--address", ":9000", "--console-address", ":9001", "/data"]
            ports:
              - containerPort: 9000
              - containerPort: 9001
            env:
              - name: MINIO_ACCESS_KEY
                value: "fantasticdrogon"
              - name: MINIO_SECRET_KEY
                value: "Dolmatova171204"
            volumeMounts:
              - mountPath: "/data"
                name: minio-data
        volumes:
          - name: minio-data
            emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: NodePort
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      nodePort: 30000
    - name: console
      port: 9001
      targetPort: 9001
      nodePort: 30001
  selector:
    app: minio